#!/bin/bash
#
# bash_aliases
#
# This file is copied into the home directory of the vagrant user on the virtual
# machine during provisioning and is included in the .bashrc automatically as
# provisioning is finished. This allows for various scripts and configurations to
# be available to us.
#


###
### basic linux shortcuts
###

alias nw='nano -w'
alias syslog='tail -f /var/log/syslog'
alias ls='ls --color=auto'
alias ll='ls -l'
alias ..='cd ..' 
alias ...='cd ../../'

# display PATH in human readable form
alias path='echo -e ${PATH//:/\\n}' 

# recursive chmod and chown
alias chmodr='chmod -R'
alias chownr='chown -R'


###
### favourite directories
###

alias cdwp='cd /srv/www/wordpress-default'
alias cdp='cd wp-content/plugins'
alias cdt='cd wp-content/themes'
alias cdwpp='cdwp && cdp'

###
### ack
###

alias cuthere='echo -e "\n-------------------------------------------------- cut here --------------------------------------------------\n\n\n"'
alias ack='cuthere; ack-grep'


###
### subversion
###

# i never remember this one
alias colourdiff='colordiff'

# too long!
alias svnlog='svn log | head -n 50'

# too gray!
alias svndiff='svn diff | colourdiff'


###
### otgs tools 
###

# get wp paths from anywhere within WordPress instalation
function wp_content_dir {
	wp eval 'echo WP_CONTENT_DIR;'
}

function wp_plugins_dir {
	content_dir=`wp_content_dir`
	echo $content_dir/plugins
}

# switch between embedded and full views

function views_embedded {
	plugins_dir=`wp_plugins_dir`
	wp plugin deactivate wp-views
	mv "$plugins_dir/wp-views/embedded" "$plugins_dir/embedded-views"
	wp plugin activate embedded-views
}

function views_full {
	wp plugin deactivate embedded-views
	mv "$plugins_dir/embedded-views" "$plugins_dir/wp-views/embedded"
	wp plugin activate wp-views
}



# activate all toolset plugins

alias toolset_activate='wp plugin activate types wp-views cred-frontend-editor layouts types-access'


###
### Greeting, motd etc. ...
###

# Color definitions (taken from Color Bash Prompt HowTo).
# Some colors might look different of some terminals.
# For example, I see 'Bold Red' as 'orange' on my screen,
# hence the 'Green' 'BRed' 'Red' sequence I often use in my prompt.


# Normal Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

NC="\e[m"               # Color Reset

ALERT=${BWhite}${On_Red} # Bold White on red background

alias say_vov='figlet -cf slant VOV'