#!/bin/bash
#
# bash_aliases
#
# This file is copied into the home directory of the vagrant user on the virtual
# machine during provisioning and is included in the .bashrc automatically as
# provisioning is finished. This allows for various scripts and configurations to
# be available to us.
#


###
### terminal output formatting
###
COLOUR_BTW='\033[90m'
COLOUR_WHITE='\033[01;37m'
COLOUR_YELLOW='\033[01;33m'
COLOUR_RESTORE='\033[0m'
COLOUR_RED='\033[91m'
COLOUR_LIGHT_GRAY='\033[0;37m'


function say_vov {
	figlet -cf slant VOV
}


function echo_w {
    echo -e "$COLOUR_WHITE$1$COLOUR_RESTORE"
}

function echo_y {
    echo -e "$COLOUR_YELLOW$1$COLOUR_RESTORE"
}

function echo_g {
	echo -e "$COLOUR_LIGHT_GRAY$1$COLOUR_RESTORE"
}


###
### basic linux shortcuts
###

alias nw='nano -w'
alias syslog='tail -f /var/log/syslog'
alias ls='ls --color=auto'
alias ll='ls -l'
alias ..='cd ..' 
alias ...='cd ../../'

# display PATH in human readable form
alias path='echo -e ${PATH//:/\\n}' 

# recursive chmod and chown
alias chmodr='chmod -R'
alias chownr='chown -R'


###
### favourite directories
###

alias cdwp='cd /srv/www/wordpress-default'
alias cdp='cd wp-content/plugins'
alias cdt='cd wp-content/themes'
alias cdwpp='cdwp && cdp'

alias cdv='cdwpp && cd wp-views'
alias cdt='cdwpp && cd types'
alias cdl='cdwpp && cd layouts'

###
### ack
###

alias cuthere='echo -e "\n-------------------------------------------------- cut here --------------------------------------------------\n\n\n"'
alias ack='cuthere; ack-grep'


###
### subversion
###

# i never remember this one
alias colourdiff='colordiff'

# too long!
alias svnlog='svn log | head -n 50'

# too gray!
alias svndiff='svn diff | colourdiff'


###
### otgs tools 
###

# get wp paths from anywhere within WordPress instalation
function wp_content_dir {
	wp eval 'echo WP_CONTENT_DIR;'
}

function wp_plugins_dir {
	content_dir=`wp_content_dir`
	echo $content_dir/plugins
}

# switch between embedded and full views

function views_embedded {
	say_vov
	echo_w "Switching to embedded Views..."
	local plugins_dir=`wp_plugins_dir`

	echo "Deactivating wp-views"
	wp plugin deactivate wp-views

	echo "Moving plugin files"
	mv "$plugins_dir/wp-views/embedded" "$plugins_dir/embedded-views"

	echo "Activating embedded-views"
	wp plugin activate embedded-views

	echo
	echo_y "Embedded Views is now active"
	echo
}

function views_full {
	say_vov
	echo_w "Switching to full Views..."
	local plugins_dir=`wp_plugins_dir`

	echo "Deactivating embedded-views"
	wp plugin deactivate embedded-views

	echo "Moving plugin files"
	mv "$plugins_dir/embedded-views" "$plugins_dir/wp-views/embedded"

	echo "Activating wp-views"
	wp plugin activate wp-views

	echo
	echo_y "Full Views is now active"
	echo
}


# switch between embedded and full
function types_embedded {
	say_vov
	echo_w "Switching to embedded Types..."
	local plugins_dir=`wp_plugins_dir`

	echo "Deactivating types"
	wp plugin deactivate types

	echo "Moving plugin files"
	mv "$plugins_dir/types/embedded" "$plugins_dir/embedded-types"

	echo "Activating embedded-types"
	wp plugin activate embedded-types

	echo
	echo_y "Embedded Types is now active"
	echo
}


function types_full {
	say_vov
	echo_w "Switching to full Types..."
	local plugins_dir=`wp_plugins_dir`

	echo "Deactivating embedded-types"
	wp plugin deactivate embedded-types

	echo "Moving plugin files"
	mv "$plugins_dir/embedded-types" "$plugins_dir/types/embedded"

	echo "Activating types"
	wp plugin activate types

	echo
	echo_y "Full Types is now active"
	echo
}



# activate all toolset plugins

alias toolset_activate='wp plugin activate types wp-views cred-frontend-editor layouts types-access'


###
### Greeting, motd etc. ...
###

# Color definitions (taken from Color Bash Prompt HowTo).
# Some colors might look different of some terminals.
# For example, I see 'Bold Red' as 'orange' on my screen,
# hence the 'Green' 'BRed' 'Red' sequence I often use in my prompt.


# Normal Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White

# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

# Background
On_Black='\e[40m'       # Black
On_Red='\e[41m'         # Red
On_Green='\e[42m'       # Green
On_Yellow='\e[43m'      # Yellow
On_Blue='\e[44m'        # Blue
On_Purple='\e[45m'      # Purple
On_Cyan='\e[46m'        # Cyan
On_White='\e[47m'       # White

NC="\e[m"               # Color Reset

ALERT=${BWhite}${On_Red} # Bold White on red background